"""new_arch_users_ai_logs_judge_verdicts_extend_runs

Revision ID: a8e47e0cc690
Revises: dc8a2216891c
Create Date: 2026-09-09 12:52:45.589110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a8e47e0cc690'
down_revision = 'dc8a2216891c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_call_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('subphase', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge_verdicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('forced_pass', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    op.add_column('itinerary_stops', sa.Column('justification', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('paused', sa.Boolean(), nullable=False))
    op.add_column('runs', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('paused_at_stage', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('paused_at_subphase', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('low_confidence', sa.Boolean(), nullable=False))
    op.add_column('runs', sa.Column('low_confidence_stages', sa.JSON(), nullable=False))
    op.add_column('runs', sa.Column('stage_plans', sa.JSON(), nullable=False))
    op.add_column('runs', sa.Column('retry_counts', sa.JSON(), nullable=False))
    op.alter_column('runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('runs', 'retry_counts')
    op.drop_column('runs', 'stage_plans')
    op.drop_column('runs', 'low_confidence_stages')
    op.drop_column('runs', 'low_confidence')
    op.drop_column('runs', 'paused_at_subphase')
    op.drop_column('runs', 'paused_at_stage')
    op.drop_column('runs', 'paused_at')
    op.drop_column('runs', 'paused')
    op.drop_column('itinerary_stops', 'justification')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'user_id')
    op.drop_table('judge_verdicts')
    op.drop_table('ai_call_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
